export interface CuratedEventSeed {
  slug: string;
  title: string;
  fact: string;
  summary: string;
  technical: string;
  industry: string;
  future: string;
  business: string;
  category: string;
  company: string;
  keywords: readonly string[];
  scores: readonly [confidence: number, heat: number, impact: number, value: number];
  date: string;
  source: string;
  url: string;
  tracks: readonly string[];
  actors: readonly string[];
}

const event = (value: CuratedEventSeed): CuratedEventSeed => value;

/**
 * Editorially selected milestones for the two-year window. These are not a news archive:
 * every row must represent a durable change and link to a first-party source.
 */
export const historicalEvents = [
  event({
    slug: "llama-3-1-open-frontier-model",
    title: "Llama 3.1 405B 发布：开放权重第一次进入前沿模型竞争",
    fact: "Meta 发布 Llama 3.1 405B、70B 与 8B 模型，扩展到 128K 上下文并开放权重下载。",
    summary:
      "开放模型从追随路线进入可与闭源前沿模型直接比较的阶段，云厂商和开发者获得了可控制、可蒸馏的基础模型资产。",
    technical: "405B 模型、FP8 推理和合成数据/蒸馏工具链，证明开放生态也能组织超大规模训练与部署。",
    industry: "模型竞争从单一 API 变成闭源能力、开放权重和云分发三种路线并存。",
    future: "观察开放模型在真实企业工作负载中的使用量、衍生模型质量和推理成本。",
    business: "To D 团队获得更强的私有化和模型定制底座；模型厂商必须用产品和服务维持闭源溢价。",
    category: "model-release",
    company: "Meta",
    keywords: ["Llama 3.1", "开放权重", "405B", "蒸馏"],
    scores: [98, 0, 94, 91],
    date: "2024-07-23T00:00:00.000Z",
    source: "meta-ai",
    url: "https://ai.meta.com/blog/meta-llama-3-1/",
    tracks: ["tech-evolution", "agi-progress", "to-d", "commercialization"],
    actors: ["meta"],
  }),
  event({
    slug: "eu-ai-act-enters-force",
    title: "欧盟 AI Act 生效：通用模型进入正式合规周期",
    fact: "欧盟《人工智能法案》于 2024 年 8 月 1 日生效，并为通用模型和高风险系统设置分阶段义务。",
    summary: "AI 治理从原则讨论进入产品、模型、数据和供应链责任可执行的阶段。",
    technical: "模型文档、风险评估、透明度和系统级监控开始成为工程交付的一部分。",
    industry: "进入欧洲市场的模型与应用厂商需要把合规成本前置，政策能力成为 To B/To G 竞争门槛。",
    future: "观察 GPAI 义务、实施准则和高风险系统标准如何改变模型发布与采购。",
    business: "企业采购需要同时评估模型能力、部署地区、数据边界和法规责任。",
    category: "policy",
    company: "European Union",
    keywords: ["EU AI Act", "GPAI", "合规", "To G"],
    scores: [99, 0, 92, 90],
    date: "2024-08-01T00:00:00.000Z",
    source: "eu-ai-office",
    url: "https://digital-strategy.ec.europa.eu/en/news/european-artificial-intelligence-act-comes-force",
    tracks: ["commercialization", "investing", "to-b", "to-g"],
    actors: [],
  }),
  event({
    slug: "openai-o1-test-time-reasoning",
    title: "OpenAI o1 预览：能力扩展从训练 Scaling 转向推理时计算",
    fact: "OpenAI 发布 o1-preview 与 o1-mini，模型会在回答前投入更多推理计算。",
    summary: "推理时计算成为新的能力杠杆，行业开始从即时生成转向可分配思考预算的问题求解。",
    technical: "强化学习和长链推理让数学、代码与科学问题的性能随推理预算增长。",
    industry: "模型定价、延迟和能力不再是一条固定曲线，推理基础设施与任务路由的重要性上升。",
    future: "观察可验证推理、错误恢复、长链成本和推理过程可控性。",
    business: "高价值复杂任务可以接受更高延迟与成本，企业应按任务价值而非统一 token 单价选模。",
    category: "reasoning",
    company: "OpenAI",
    keywords: ["o1", "推理时计算", "强化学习", "reasoning"],
    scores: [99, 0, 98, 95],
    date: "2024-09-12T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-openai-o1-preview/",
    tracks: ["tech-evolution", "agi-progress", "model-economics", "to-d"],
    actors: ["openai"],
  }),
  event({
    slug: "qwen-2-5-open-model-matrix",
    title: "Qwen2.5 发布：中国开放模型形成全尺寸与垂直模型矩阵",
    fact: "阿里巴巴 Qwen 团队发布 Qwen2.5 系列，覆盖 0.5B 到 72B，并扩展代码、数学和视觉语言模型。",
    summary:
      "中国模型竞争从单点旗舰转向尺寸、任务和部署形态完整覆盖，开放生态成为追赶全球前沿的重要路径。",
    technical: "统一模型家族降低了从端侧到云端、从通用到代码/数学任务的迁移成本。",
    industry: "阿里把模型、云 API 与开源社区连接起来，强化国内开发者分发和海外影响力。",
    future: "观察海外开发者采用、端侧部署、企业微调和与国际前沿模型的差距变化。",
    business: "国内 To D 团队获得低门槛模型底座，云厂商可通过托管、数据与工具链承接商业价值。",
    category: "model-release",
    company: "Alibaba / Qwen",
    keywords: ["Qwen2.5", "开放模型", "中国追赶", "模型矩阵"],
    scores: [97, 0, 90, 90],
    date: "2024-09-19T00:00:00.000Z",
    source: "qwen",
    url: "https://qwenlm.github.io/blog/qwen2.5/",
    tracks: ["tech-evolution", "china-catch-up", "to-d", "commercialization"],
    actors: ["alibaba"],
  }),
  event({
    slug: "claude-computer-use",
    title: "Claude Computer Use：模型开始直接操作通用软件界面",
    fact: "Anthropic 发布计算机使用能力测试版，Claude 可以观察屏幕并操作鼠标和键盘。",
    summary:
      "Agent 不再依赖每个应用提供专用 API，通用界面操作打开了更广的自动化空间，也暴露出可靠性与安全难题。",
    technical: "视觉定位、操作规划、状态反馈和长任务纠错第一次被组合成通用桌面执行能力。",
    industry: "RPA、浏览器自动化和模型 Agent 的边界开始融合。",
    future: "观察真实任务成功率、提示注入防护、权限隔离和人工接管。",
    business: "优先选择可验证、可回滚的窄流程，避免把演示成功率直接等同生产 ROI。",
    category: "agent",
    company: "Anthropic",
    keywords: ["Computer Use", "Agent", "GUI", "自动化"],
    scores: [98, 0, 95, 94],
    date: "2024-10-22T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/3-5-models-and-computer-use",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "to-b", "to-d"],
    actors: ["anthropic"],
  }),
  event({
    slug: "model-context-protocol",
    title: "MCP 开源：Agent 的工具连接开始形成公共协议",
    fact: "Anthropic 开源 Model Context Protocol，用统一方式连接 AI 助手、数据源和工具。",
    summary:
      "模型与外部系统的连接从厂商私有插件走向可复用协议，Agent 生态开始出现类似 USB 的接口层。",
    technical: "Client、server、resource 与 tool 的标准化降低了上下文接入和工具复用成本。",
    industry: "竞争焦点从谁拥有最多插件转向谁控制客户端、权限、目录和运行时。",
    future: "观察跨厂商支持、鉴权、安全沙箱、远程 MCP 和企业治理。",
    business: "To D 公司应优先提供协议兼容的能力资产，而非只绑定单一模型平台。",
    category: "developer-platform",
    company: "Anthropic",
    keywords: ["MCP", "Agent 协议", "工具调用", "生态"],
    scores: [98, 0, 96, 96],
    date: "2024-11-25T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/model-context-protocol",
    tracks: ["tech-evolution", "to-d", "commercialization"],
    actors: ["anthropic"],
  }),
  event({
    slug: "gemini-2-agentic-era",
    title: "Gemini 2.0 发布：Google 把多模态模型推进到 Agent 系统",
    fact: "Google 发布 Gemini 2.0 Flash，并展示 Project Astra、Mariner 和代码 Agent 等原型。",
    summary:
      "模型能力被组织为感知、推理、工具使用和行动的完整系统，Google 开始把搜索、浏览器、Android 与模型结合。",
    technical: "原生多模态输入输出、工具调用和低延迟推理让实时 Agent 成为产品主线。",
    industry: "拥有浏览器、移动操作系统和搜索入口的平台获得结构性分发优势。",
    future: "观察原型向稳定产品转化的速度，以及跨产品权限和用户信任。",
    business: "独立 Agent 产品必须拥有 Google 难以复制的行业流程、数据或交付闭环。",
    category: "model-release",
    company: "Google DeepMind",
    keywords: ["Gemini 2.0", "Project Astra", "Mariner", "多模态 Agent"],
    scores: [98, 0, 96, 95],
    date: "2024-12-11T00:00:00.000Z",
    source: "google-ai",
    url: "https://blog.google/technology/google-deepmind/google-gemini-ai-update-december-2024/",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "to-c", "to-d"],
    actors: ["google"],
  }),
  event({
    slug: "deepseek-v3-efficient-frontier",
    title: "DeepSeek-V3 开源：训练效率成为中国追赶的新叙事",
    fact: "DeepSeek 发布并开放 DeepSeek-V3 权重与技术报告，采用 671B MoE、37B 激活参数和 FP8 训练。",
    summary:
      "DeepSeek 用架构、系统和工程协同压低前沿模型训练成本，改变了中国模型只能依赖更大资源追赶的判断。",
    technical: "MLA、DeepSeekMoE、无辅助损失负载均衡、MTP 和 FP8 共同提升训练与推理效率。",
    industry: "模型竞争增加了单位算力产出这一核心维度，并推动国内硬件与推理栈适配。",
    future: "观察独立复现、真实 API 负载、国产算力适配和后续推理模型。",
    business: "成本效率会压缩通用 API 毛利，但扩大模型进入低客单价业务的空间。",
    category: "model-release",
    company: "DeepSeek",
    keywords: ["DeepSeek-V3", "MoE", "FP8", "训练效率"],
    scores: [98, 0, 97, 96],
    date: "2024-12-26T00:00:00.000Z",
    source: "deepseek",
    url: "https://github.com/deepseek-ai/DeepSeek-V3",
    tracks: ["tech-evolution", "china-catch-up", "model-economics", "to-d", "investing"],
    actors: ["deepseek"],
  }),
  event({
    slug: "deepseek-r1-open-reasoning",
    title: "DeepSeek-R1 开源：推理能力与低成本冲击全球模型格局",
    fact: "DeepSeek 发布 R1、R1-Zero 和蒸馏模型，公开权重与技术方法。",
    summary:
      "中国团队把前沿推理能力、开放权重和极具竞争力的价格组合起来，促使全球市场重新评估算力壁垒和模型定价。",
    technical: "纯强化学习、冷启动、多阶段训练和蒸馏展示了可复用的推理能力构建路线。",
    industry: "开放推理模型加速价格下降，并让中国模型第一次成为全球开发者和资本市场的共同变量。",
    future: "观察真实工具使用、长任务可靠性、蒸馏生态和下一代训练成本。",
    business: "通用模型溢价承压，应用公司更应把价值建立在数据、流程和分发而非模型转售。",
    category: "reasoning",
    company: "DeepSeek",
    keywords: ["DeepSeek-R1", "推理", "强化学习", "开放权重"],
    scores: [99, 0, 99, 99],
    date: "2025-01-20T00:00:00.000Z",
    source: "deepseek",
    url: "https://github.com/deepseek-ai/DeepSeek-R1",
    tracks: ["tech-evolution", "agi-progress", "china-catch-up", "investing", "model-economics"],
    actors: ["deepseek"],
  }),
  event({
    slug: "openai-operator-browser-agent",
    title: "Operator 发布：OpenAI 从对话产品进入浏览器任务执行",
    fact: "OpenAI 发布 Operator 研究预览，模型可以在浏览器中点击、输入并完成多步骤任务。",
    summary:
      "ChatGPT 的产品边界从回答问题扩展到代替用户执行，消费级 Agent 开始验证真实交易与服务流程。",
    technical: "Computer-Using Agent 将视觉、推理和交互动作放进闭环，但仍需要频繁的人类确认。",
    industry: "浏览器成为 Agent 的通用执行层，电商、旅行和本地服务平台需要重新考虑机器用户。",
    future: "观察支付/登录场景、反自动化策略、成功率和责任边界。",
    business: "To C Agent 的核心指标应从使用时长转为完成任务数、节省时间和交易转化。",
    category: "agent-product",
    company: "OpenAI",
    keywords: ["Operator", "Browser Agent", "CUA", "To C"],
    scores: [98, 0, 95, 94],
    date: "2025-01-23T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-operator/",
    tracks: ["tech-evolution", "commercialization", "to-c", "agi-progress"],
    actors: ["openai"],
  }),
  event({
    slug: "openai-deep-research",
    title: "Deep Research 发布：Agent 首次把复杂知识工作做成标准产品",
    fact: "OpenAI 在 ChatGPT 发布 Deep Research，可自主搜索、分析并综合大量在线来源。",
    summary:
      "长时研究任务成为可购买的消费与专业能力，Agent 的价值从即时回答转向替代数小时知识劳动。",
    technical: "浏览、检索、证据选择、长上下文推理和报告生成被组合成持续数十分钟的工作流。",
    industry: "研究、咨询、投研和专业信息服务开始面对结果型 AI 产品的直接竞争。",
    future: "观察引用准确性、付费使用量、垂直数据库接入和结果责任。",
    business: "专业服务团队应把 AI 用于扩大研究覆盖，并把差异化转向私有数据与判断框架。",
    category: "agent-product",
    company: "OpenAI",
    keywords: ["Deep Research", "研究 Agent", "知识工作", "ChatGPT"],
    scores: [98, 0, 96, 97],
    date: "2025-02-02T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-deep-research/",
    tracks: ["agi-progress", "commercialization", "to-c", "to-b"],
    actors: ["openai"],
  }),
  event({
    slug: "claude-3-7-code-preview",
    title: "Claude 3.7 与 Claude Code：混合推理进入开发者工作流",
    fact: "Anthropic 发布 Claude 3.7 Sonnet，并预览在终端中工作的 Claude Code。",
    summary: "模型厂商不再只提供模型能力，而是直接占据代码库、终端和工程任务入口。",
    technical: "可控扩展思考与 Agent 工具循环结合，让模型在速度、成本和任务深度之间动态取舍。",
    industry: "编码助手从补全和聊天升级为能规划、修改、测试与提交的工程协作者。",
    future: "观察真实 PR 合并率、长任务恢复、代码安全和团队级治理。",
    business: "开发工具市场的价值将集中到上下文、执行环境、评测和组织工作流。",
    category: "coding-agent",
    company: "Anthropic",
    keywords: ["Claude 3.7", "Claude Code", "混合推理", "编码 Agent"],
    scores: [99, 0, 97, 98],
    date: "2025-02-24T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/claude-3-7-sonnet",
    tracks: ["tech-evolution", "agi-progress", "to-d", "commercialization"],
    actors: ["anthropic"],
  }),
  event({
    slug: "openai-responses-agents-sdk",
    title: "Responses API 与 Agents SDK：OpenAI 建立 Agent 开发平台",
    fact: "OpenAI 发布 Responses API、内置 Web/File/Computer Use 工具和开源 Agents SDK。",
    summary:
      "Agent 从应用团队自组装的框架变成模型平台的标准产品层，工具、追踪和编排被纳入统一 API。",
    technical: "托管工具、handoff、tracing 和状态管理降低了多步 Agent 的工程门槛。",
    industry: "模型 API 厂商开始向 Agent runtime 扩张，与开源框架和自动化平台正面竞争。",
    future: "观察锁定成本、跨模型兼容、可观测性和企业权限治理。",
    business: "To D 产品需要在开放性、行业组件或运行治理上建立差异化。",
    category: "developer-platform",
    company: "OpenAI",
    keywords: ["Responses API", "Agents SDK", "工具调用", "开发平台"],
    scores: [99, 0, 95, 97],
    date: "2025-03-11T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/new-tools-for-building-agents/",
    tracks: ["tech-evolution", "to-d", "commercialization"],
    actors: ["openai"],
  }),
  event({
    slug: "nvidia-blackwell-ultra-reasoning-factory",
    title: "Blackwell Ultra 发布：推理时 Scaling 重塑 AI 基础设施",
    fact: "NVIDIA 在 GTC 2025 发布 Blackwell Ultra、Dynamo 和面向推理 Agent 的 AI Factory 平台。",
    summary: "算力需求从集中训练扩展到持续、高并发、长链推理，推理吞吐和数据中心协同成为新瓶颈。",
    technical: "GB300、Dynamo、网络和存储共同围绕 test-time scaling 与 Agent 工作负载优化。",
    industry: "芯片价值继续向完整系统、网络、软件和电力基础设施延伸。",
    future: "观察推理收入占比、集群利用率、能源约束和替代加速器。",
    business: "投资判断要从 GPU 出货转向单位推理产出、部署周期和数据中心现金流。",
    category: "infrastructure",
    company: "NVIDIA",
    keywords: ["Blackwell Ultra", "Dynamo", "推理基础设施", "AI Factory"],
    scores: [99, 0, 97, 96],
    date: "2025-03-18T00:00:00.000Z",
    source: "nvidia-blog-ai",
    url: "https://nvidianews.nvidia.com/online-press-kit/gtc-2025-news",
    tracks: ["tech-evolution", "investing", "model-economics", "to-b"],
    actors: ["nvidia"],
  }),
  event({
    slug: "gemini-2-5-thinking-model",
    title: "Gemini 2.5 发布：思考模型成为前沿模型默认形态",
    fact: "Google 发布 Gemini 2.5 Pro 实验版，将推理能力内置为模型的核心能力。",
    summary: "推理从独立产品线变为旗舰模型的默认属性，长上下文、多模态与思考开始合流。",
    technical: "大上下文、代码能力和推理时计算共同面向复杂 Agent 与知识任务。",
    industry: "前沿厂商竞争从是否有 reasoning model 转向单位成本、延迟和产品整合。",
    future: "观察稳定版价格、工具使用、长上下文有效利用率和企业分发。",
    business: "应用团队应减少对固定模型标签的依赖，建立任务级路由和持续评测。",
    category: "reasoning",
    company: "Google DeepMind",
    keywords: ["Gemini 2.5", "Thinking Model", "长上下文", "推理"],
    scores: [98, 0, 96, 94],
    date: "2025-03-25T00:00:00.000Z",
    source: "google-ai",
    url: "https://blog.google/technology/google-deepmind/gemini-model-thinking-updates-march-2025/",
    tracks: ["tech-evolution", "agi-progress", "model-economics", "to-d"],
    actors: ["google"],
  }),
  event({
    slug: "llama-4-native-multimodal-moe",
    title: "Llama 4 发布：开放模型转向原生多模态 MoE",
    fact: "Meta 发布 Llama 4 Scout 与 Maverick，采用原生多模态和混合专家架构。",
    summary: "开放模型路线跟进多模态、超长上下文和稀疏激活，继续压缩闭源模型的基础能力差异。",
    technical: "MoE 让总参数规模与推理成本解耦，Scout 将上下文扩展到千万 token 级别。",
    industry: "开放生态进入复杂系统竞争，但训练透明度、评测可信度和部署门槛仍是约束。",
    future: "观察社区复现、实际上下文利用、企业部署和后续旗舰模型。",
    business: "私有化与开放权重方案更丰富，企业需要评估总拥有成本而不是只看 benchmark。",
    category: "model-release",
    company: "Meta",
    keywords: ["Llama 4", "MoE", "原生多模态", "开放模型"],
    scores: [97, 0, 91, 88],
    date: "2025-04-05T00:00:00.000Z",
    source: "meta-ai",
    url: "https://ai.meta.com/blog/llama-4-multimodal-intelligence/",
    tracks: ["tech-evolution", "to-d", "commercialization"],
    actors: ["meta"],
  }),
  event({
    slug: "google-a2a-agent-protocol",
    title: "Google A2A 发布：多 Agent 协作进入协议竞争",
    fact: "Google 联合多家企业发布 Agent2Agent Protocol，用于不同平台和厂商 Agent 之间协作。",
    summary: "在 MCP 解决 Agent 与工具连接之后，A2A 把标准化推进到 Agent 身份、任务和结果交换。",
    technical: "Agent Card、任务生命周期、消息与 artifact 形成跨组织协作的公共抽象。",
    industry: "Agent 生态开始从单体应用转向协议、目录、身份和治理组成的网络。",
    future: "观察 MCP/A2A 分工、企业身份、跨域授权和实际互操作案例。",
    business: "平台型产品应把能力封装为可发现、可授权、可审计的 Agent 服务。",
    category: "developer-platform",
    company: "Google",
    keywords: ["A2A", "Agent2Agent", "互操作", "协议"],
    scores: [98, 0, 92, 94],
    date: "2025-04-09T00:00:00.000Z",
    source: "google-developers",
    url: "https://developers.googleblog.com/en/a2a-a-new-era-of-agent-interoperability/",
    tracks: ["tech-evolution", "to-d", "to-b", "commercialization"],
    actors: ["google"],
  }),
  event({
    slug: "openai-o3-o4-mini-tools",
    title: "o3 与 o4-mini 发布：推理模型开始主动调用全套工具",
    fact: "OpenAI 发布 o3 和 o4-mini，并让推理模型在 ChatGPT 中组合使用浏览、代码、文件和图像工具。",
    summary: "推理与行动合流，模型从在单一上下文中思考转向选择工具、验证结果并完成任务。",
    technical: "模型原生工具选择把规划、执行和检查纳入统一推理过程。",
    industry: "Agent 能力逐渐内建进旗舰模型，纯编排层产品面临价值压缩。",
    future: "观察工具选择准确性、错误恢复、长任务成本和安全控制。",
    business: "应用公司的壁垒需要从调用链转向数据、权限、评测和业务闭环。",
    category: "reasoning",
    company: "OpenAI",
    keywords: ["o3", "o4-mini", "工具使用", "Agent"],
    scores: [99, 0, 97, 96],
    date: "2025-04-16T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-o3-and-o4-mini/",
    tracks: ["tech-evolution", "agi-progress", "to-c", "to-d"],
    actors: ["openai"],
  }),
  event({
    slug: "qwen-3-hybrid-thinking",
    title: "Qwen3 开源：中国模型进入混合推理与 Agent 阶段",
    fact: "Qwen 团队发布 Qwen3 系列开放模型，支持 thinking/non-thinking 切换与多语言能力。",
    summary: "国产开放模型快速吸收推理时计算和 MoE 路线，并把成本、尺寸和部署选择做成完整矩阵。",
    technical: "混合推理允许同一模型按任务切换思考预算，MoE 提升参数容量与推理效率。",
    industry: "中国模型与全球前沿的技术代差缩短，竞争转向生态、产品、算力和海外分发。",
    future: "观察 Agent 工具使用、海外采用、企业落地和下一代旗舰模型。",
    business: "国内 To D 市场的模型供给更充分，价值继续向工具链和行业数据迁移。",
    category: "model-release",
    company: "Alibaba / Qwen",
    keywords: ["Qwen3", "混合推理", "MoE", "中国追赶"],
    scores: [98, 0, 94, 94],
    date: "2025-04-29T00:00:00.000Z",
    source: "qwen",
    url: "https://qwenlm.github.io/blog/qwen3/",
    tracks: ["tech-evolution", "agi-progress", "china-catch-up", "to-d"],
    actors: ["alibaba"],
  }),
  event({
    slug: "openai-codex-cloud-agent",
    title: "Codex 云端 Agent 发布：编码任务从辅助转向委派",
    fact: "OpenAI 发布 Codex 研究预览，可在隔离云环境中并行处理代码库任务。",
    summary:
      "开发者可以把修复、测试和代码理解任务交给后台 Agent，编码产品从同步对话进入异步任务队列。",
    technical: "隔离环境、仓库上下文、并行执行和可审查变更是可靠编码 Agent 的关键系统能力。",
    industry: "GitHub、IDE、终端和云 Agent 开始争夺软件交付的控制面。",
    future: "观察 PR 合并率、运行成本、安全边界和团队协作模式。",
    business: "软件团队需要把 Agent 纳入权限、评审、CI 和产能度量，而不只是购买个人席位。",
    category: "coding-agent",
    company: "OpenAI",
    keywords: ["Codex", "云端 Agent", "异步编码", "软件工程"],
    scores: [98, 0, 97, 98],
    date: "2025-05-16T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-codex/",
    tracks: ["tech-evolution", "commercialization", "to-d", "to-b"],
    actors: ["openai"],
  }),
  event({
    slug: "claude-4-long-running-agents",
    title: "Claude 4 发布：长时编码与 Agent 能力成为旗舰卖点",
    fact: "Anthropic 发布 Claude Opus 4 与 Sonnet 4，强调编码、工具使用和长任务能力。",
    summary: "前沿模型的评价中心继续从聊天质量转向可持续执行真实工作的可靠性。",
    technical: "混合推理、并行工具、记忆与长任务行为围绕 Agent 工作负载优化。",
    industry: "Anthropic 以 Claude Code 和企业 API 将模型优势直接转化为开发者与企业产品。",
    future: "观察长任务成功率、Agent 安全等级、企业收入和模型成本。",
    business: "编码与知识工作成为模型商业化最清晰的高价值入口。",
    category: "model-release",
    company: "Anthropic",
    keywords: ["Claude 4", "Opus 4", "Sonnet 4", "长任务"],
    scores: [99, 0, 97, 98],
    date: "2025-05-22T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/claude-4",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "to-d", "to-b"],
    actors: ["anthropic"],
  }),
  event({
    slug: "minimax-m1-long-context-reasoning",
    title: "MiniMax-M1 开源：国产推理模型竞争延伸到百万上下文",
    fact: "MiniMax 发布并开源 M1 混合注意力推理模型，提供百万 token 输入上下文。",
    summary: "国产模型厂商开始在推理、长上下文、Agent 工具使用和成本之间寻找差异化路线。",
    technical: "Lightning Attention 与混合注意力降低长上下文计算成本，面向复杂生产力任务。",
    industry: "国内前沿模型从跟随单一 benchmark 转向架构和产品约束共同优化。",
    future: "观察开源复现、长上下文有效性、API 使用和 Agent 产品转化。",
    business: "长文档、代码库和企业知识场景获得更低成本的国产模型选项。",
    category: "reasoning",
    company: "MiniMax",
    keywords: ["MiniMax-M1", "长上下文", "混合注意力", "开源"],
    scores: [96, 0, 88, 88],
    date: "2025-06-16T00:00:00.000Z",
    source: "minimax",
    url: "https://www.minimax.io/news/minimaxm1",
    tracks: ["tech-evolution", "china-catch-up", "to-d", "model-economics"],
    actors: ["minimax"],
  }),
  event({
    slug: "kimi-k2-agentic-open-model",
    title: "Kimi K2 开放：Moonshot 把国产模型竞争推向 Agent 与代码",
    fact: "Moonshot AI 发布 Kimi K2 混合专家模型并开放权重，重点强化代码和 Agent 工具使用。",
    summary: "中国头部创业公司从消费级长文本产品延伸到开放基础模型和开发者生态。",
    technical: "大规模 MoE、工具调用和代码训练面向可执行 Agent，而不仅是对话体验。",
    industry: "国内模型厂商同时争夺 To C 用户、To D 生态和海外开发者。",
    future: "观察 API 收入、权重采用、工具调用可靠性和海外生态。",
    business: "创业公司需要证明开放模型能够反向增强付费产品和平台分发。",
    category: "model-release",
    company: "Moonshot AI",
    keywords: ["Kimi K2", "MoE", "Agent", "开放权重"],
    scores: [96, 0, 91, 91],
    date: "2025-07-11T00:00:00.000Z",
    source: "moonshot",
    url: "https://github.com/MoonshotAI/Kimi-K2",
    tracks: ["tech-evolution", "china-catch-up", "commercialization", "to-c", "to-d"],
    actors: ["moonshot"],
  }),
  event({
    slug: "chatgpt-agent-research-to-action",
    title: "ChatGPT Agent 发布：研究、浏览与行动合并为统一模式",
    fact: "OpenAI 发布 ChatGPT Agent，将 Operator 的操作、Deep Research 的研究和对话能力整合。",
    summary: "消费级 AI 产品从多个实验入口收敛为目标驱动的通用任务执行模式。",
    technical: "视觉浏览器、文本浏览器、终端、连接器和人工确认共同组成多工具 Agent runtime。",
    industry: "模型、产品入口和执行环境进一步合并，独立通用 Agent 的生存空间缩小。",
    future: "观察高频任务、成功率、交易安全和订阅留存。",
    business: "To C 团队应围绕结果、信任和垂直闭环，而非复制通用聊天与浏览能力。",
    category: "agent-product",
    company: "OpenAI",
    keywords: ["ChatGPT Agent", "Operator", "Deep Research", "任务执行"],
    scores: [99, 0, 98, 98],
    date: "2025-07-17T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-chatgpt-agent/",
    tracks: ["agi-progress", "commercialization", "to-c", "to-b"],
    actors: ["openai"],
  }),
  event({
    slug: "gpt-5-unified-routing",
    title: "GPT-5 发布：快模型与深度推理被统一到一个产品入口",
    fact: "OpenAI 发布 GPT-5，并在 ChatGPT 中通过统一系统路由即时回答和更深推理。",
    summary: "用户不再需要理解复杂模型菜单，模型选择开始由平台按任务难度、成本和延迟自动完成。",
    technical: "路由器、能力模型与安全策略共同决定每个请求的计算预算。",
    industry: "模型品牌让位于产品级体验，平台对成本、分发和用户反馈的控制增强。",
    future: "观察路由质量、API 迁移、单位任务成本和用户对模型人格的偏好。",
    business: "企业应建立自己的任务评测和路由策略，避免把平台默认选择当作最优解。",
    category: "model-release",
    company: "OpenAI",
    keywords: ["GPT-5", "模型路由", "推理", "ChatGPT"],
    scores: [99, 0, 99, 98],
    date: "2025-08-07T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-gpt-5/",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "model-economics"],
    actors: ["openai"],
  }),
  event({
    slug: "codex-general-availability",
    title: "Codex 正式可用：编码 Agent 从实验进入团队基础设施",
    fact: "OpenAI 宣布 Codex 正式可用，并发布 SDK、Slack 集成和企业管理能力。",
    summary: "编码 Agent 从单点云任务发展为连接 IDE、终端、团队沟通和组织管理的协作系统。",
    technical: "SDK、运行环境、权限和监控把 Agent 纳入可编程的软件交付流水线。",
    industry: "编码 Agent 的竞争开始从模型能力转向工作流覆盖、团队治理和生态嵌入。",
    future: "观察企业席位、实际代码产出、SDK 生态和安全事故率。",
    business: "软件组织需要重新定义开发者产能、评审责任和 Agent 使用政策。",
    category: "coding-agent",
    company: "OpenAI",
    keywords: ["Codex", "GA", "SDK", "团队协作"],
    scores: [99, 0, 96, 98],
    date: "2025-10-06T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/codex-now-generally-available/",
    tracks: ["commercialization", "to-d", "to-b"],
    actors: ["openai"],
  }),
  event({
    slug: "claude-constitution-2026",
    title: "Claude 新宪法发布：模型行为治理走向可审查的制度层",
    fact: "Anthropic 发布 2026 版 Claude Constitution，系统说明模型的价值、行为原则和冲突处理。",
    summary: "前沿模型治理从简单规则列表走向更完整、可讨论的行为框架，安全与产品人格开始合流。",
    technical: "宪法式训练为复杂情境中的原则权衡提供显式监督结构。",
    industry: "模型厂商需要同时竞争能力、可控性、信任和制度透明度。",
    future: "观察外部评测、行为一致性、企业可配置性和监管接受度。",
    business: "高风险行业采购需要把模型行为政策纳入技术和法律尽调。",
    category: "safety-governance",
    company: "Anthropic",
    keywords: ["Claude Constitution", "对齐", "治理", "安全"],
    scores: [98, 0, 88, 89],
    date: "2026-01-22T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/claude-new-constitution",
    tracks: ["agi-progress", "to-b", "to-g"],
    actors: ["anthropic"],
  }),
  event({
    slug: "claude-opus-4-7-agent-work",
    title: "Claude Opus 4.7 发布：前沿能力继续向复杂工作与 Agent 收敛",
    fact: "Anthropic 发布 Claude Opus 4.7，重点提升代码、Agent、视觉和多步骤任务表现。",
    summary: "模型升级的价值越来越以完成复杂工作来衡量，而不是单一知识或生成 benchmark。",
    technical: "长任务规划、工具使用、视觉理解和一致性成为统一能力包。",
    industry: "Anthropic 继续围绕 Claude Code、Cowork 和企业工作构建模型—产品闭环。",
    future: "观察真实任务完成率、企业收入、推理成本和安全边界。",
    business: "To B 竞争需要同时拥有模型、执行环境、权限和行业工作流。",
    category: "model-release",
    company: "Anthropic",
    keywords: ["Claude Opus 4.7", "Agent", "编码", "复杂工作"],
    scores: [98, 0, 95, 96],
    date: "2026-04-16T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/claude-opus-4-7",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "to-b", "to-d"],
    actors: ["anthropic"],
  }),
  event({
    slug: "gpt-5-5-real-work",
    title: "GPT-5.5 发布：模型升级围绕端到端真实工作重新定义",
    fact: "OpenAI 发布 GPT-5.5，重点提升编码、研究、数据分析、文档和跨工具操作。",
    summary: "前沿竞争从回答质量继续转向能否理解模糊目标、跨工具执行并检查结果。",
    technical: "Agentic coding、computer use、科学研究和长时执行被统一到旗舰模型。",
    industry: "模型与办公、开发和研究产品的边界进一步消失。",
    future: "观察单位任务成本、失败恢复、工作流接管和企业采用。",
    business: "CEO 应以完整流程节省和结果质量评估模型，而非只比较 token 价格。",
    category: "model-release",
    company: "OpenAI",
    keywords: ["GPT-5.5", "真实工作", "Computer Use", "Agent"],
    scores: [99, 0, 98, 98],
    date: "2026-04-23T00:00:00.000Z",
    source: "openai",
    url: "https://openai.com/index/introducing-gpt-5-5/",
    tracks: ["tech-evolution", "agi-progress", "commercialization", "to-b", "to-d"],
    actors: ["openai"],
  }),
  event({
    slug: "anthropic-series-h-scale",
    title: "Anthropic 完成 Series H：模型竞争进入资本、收入与算力共振",
    fact: "Anthropic 宣布完成 650 亿美元 Series H 融资，投后估值 9650 亿美元，并披露年化收入超过 470 亿美元。",
    summary: "前沿模型公司的资本需求、商业收入和算力扩张同步放大，行业集中度继续上升。",
    technical: "持续训练、推理服务和 Agent 产品扩张把资本开支转化为长期基础设施竞争。",
    industry:
      "模型公司正在形成接近云平台的资本密度和收入规模，创业窗口向应用、数据和垂直系统迁移。",
    future: "观察收入质量、算力承诺、企业留存和估值消化。",
    business: "投资判断应把模型收入、推理毛利、资本开支和产品粘性放在同一张表中。",
    category: "investment",
    company: "Anthropic",
    keywords: ["Series H", "融资", "算力", "企业收入"],
    scores: [99, 0, 99, 97],
    date: "2026-05-28T00:00:00.000Z",
    source: "anthropic",
    url: "https://www.anthropic.com/news/series-h",
    tracks: ["investing", "commercialization", "to-b", "model-economics"],
    actors: ["anthropic"],
  }),
] as const satisfies readonly CuratedEventSeed[];

export const industryNarratives = {
  horizon: { start: "2024-07-01", end: "2026-07-11", label: "过去两年" },
  eras: [
    {
      slug: "reasoning-and-open-frontier",
      label: "推理与开放前沿",
      period: "2024 H2",
      summary:
        "o1 打开推理时 Scaling，Llama 3.1、Qwen2.5 与 DeepSeek-V3 让开放模型和训练效率成为全球竞争变量。",
    },
    {
      slug: "cost-shock-and-agents",
      label: "成本冲击与 Agent 起点",
      period: "2025 Q1",
      summary:
        "DeepSeek-R1 重估算力壁垒，Operator、Deep Research、Claude Code 与 Agents SDK 把模型推进真实任务。",
    },
    {
      slug: "protocol-and-runtime",
      label: "协议与运行时成形",
      period: "2025 Q2",
      summary: "MCP、A2A、模型原生工具和云端编码 Agent 共同建立 Agent 的连接、执行和治理层。",
    },
    {
      slug: "product-convergence",
      label: "模型与产品合流",
      period: "2025 H2",
      summary:
        "ChatGPT Agent、GPT-5 与 Codex GA 把研究、行动、路由和团队工作流收敛进统一产品入口。",
    },
    {
      slug: "real-work-and-concentration",
      label: "真实工作与产业集中",
      period: "2026 H1",
      summary:
        "旗舰模型围绕复杂工作、科学与长任务继续升级，收入、融资、算力和分发进一步向头部集中。",
    },
  ],
  tracks: [
    {
      slug: "tech-evolution",
      thesis: "技术主轴已从预训练规模，转向推理时计算、原生多模态、工具使用和长任务可靠性。",
      now: "旗舰模型正在变成可分配思考预算、可跨工具行动的执行系统。",
      next: "下一阶段胜负取决于长任务成功率、记忆、验证、恢复和单位任务成本。",
      stages: [
        {
          period: "2024 H2",
          label: "Reasoning",
          summary: "推理时计算成为新 Scaling 轴。",
          chinaPosition: "Qwen 与 DeepSeek 通过开放和效率快速跟进。",
        },
        {
          period: "2025 H1",
          label: "Tool use",
          summary: "模型原生调用浏览器、代码和文件工具。",
          chinaPosition: "国产模型进入混合推理和长上下文竞争。",
        },
        {
          period: "2025 H2–2026 H1",
          label: "Long-horizon work",
          summary: "模型围绕复杂工作和持续执行优化。",
          chinaPosition: "技术差距收窄，产品与生态仍是主要差距。",
        },
      ],
    },
    {
      slug: "agi-progress",
      thesis:
        "AGI 的可观察进展不再是单项考试分数，而是跨领域推理、工具行动、长任务和自我检查的组合。",
      now: "研究、编码、软件操作和科学任务已经出现可重复的有限自治。",
      next: "需要关注真实完成率、反证、失效条件和能力增长带来的治理升级。",
      stages: [
        {
          period: "2024 H2",
          label: "Deliberation",
          summary: "模型学会投入更多计算思考。",
          chinaPosition: "中国路线迅速转向强化学习与推理。",
        },
        {
          period: "2025",
          label: "Action",
          summary: "模型连接工具并承担数十分钟任务。",
          chinaPosition: "开源推理领先性增强，通用 Agent 产品仍在追赶。",
        },
        {
          period: "2026 H1",
          label: "Real work",
          summary: "能力评价转向端到端工作和科学。",
          chinaPosition: "需观察高价值任务和全球分发中的真实份额。",
        },
      ],
    },
    {
      slug: "commercialization",
      thesis: "商业化从 API token 消费，转向订阅、席位、任务结果和嵌入核心工作流。",
      now: "编码和知识工作率先形成高价值付费，模型厂商直接向应用和运行时扩张。",
      next: "关键指标将从调用量转为完成任务、留存、毛利和组织产能。",
      stages: [
        {
          period: "2024 H2",
          label: "Copilot",
          summary: "助手嵌入软件，但价值仍以功能辅助为主。",
          chinaPosition: "消费入口扩张快，企业付费仍弱。",
        },
        {
          period: "2025",
          label: "Agent product",
          summary: "研究、浏览和编码出现结果型产品。",
          chinaPosition: "模型价格竞争激烈，应用闭环仍在形成。",
        },
        {
          period: "2026 H1",
          label: "Workflow ownership",
          summary: "模型厂商争夺完整工作流和组织预算。",
          chinaPosition: "云与大厂分发占优，创业公司需深耕行业。",
        },
      ],
    },
    {
      slug: "investing",
      thesis: "资本主线从模型融资，扩展到芯片、数据中心、电力、云承诺和高价值应用。",
      now: "头部模型公司正在形成云平台级资本密度，基础设施与收入规模同步放大。",
      next: "需要同时跟踪训练/推理 CapEx、收入质量、毛利和平台锁定。",
      stages: [
        {
          period: "2024 H2",
          label: "Training race",
          summary: "资本主要押注更大训练集群。",
          chinaPosition: "算力限制推动系统效率和国产适配。",
        },
        {
          period: "2025",
          label: "Inference buildout",
          summary: "推理、Agent 和 AI Factory 成为新增投入。",
          chinaPosition: "DeepSeek 证明效率可以改变资本叙事。",
        },
        {
          period: "2026 H1",
          label: "Concentration",
          summary: "收入与融资进一步集中到头部。",
          chinaPosition: "融资和算力差距扩大，开放生态与成本仍有优势。",
        },
      ],
    },
    {
      slug: "china-catch-up",
      thesis:
        "中国追赶从复制产品和扩大参数，转向开放权重、训练效率、低价 API、模型矩阵和国产算力适配。",
      now: "推理与开放模型已进入全球牌桌，但全球产品分发、企业收入和前沿算力仍有差距。",
      next: "决定位置的是海外开发者采用、真实 Agent 产品、国产算力闭环和商业收入。",
      stages: [
        {
          period: "2024 H2",
          label: "Matrix",
          summary: "Qwen 建立完整开放模型矩阵。",
          chinaPosition: "从单点跟随进入生态覆盖。",
        },
        {
          period: "2025 Q1",
          label: "Efficiency shock",
          summary: "DeepSeek-V3/R1 改写全球成本认知。",
          chinaPosition: "在开放推理与效率上实现阶段性领先。",
        },
        {
          period: "2025 H2–2026 H1",
          label: "Product test",
          summary: "竞争转向 Agent、分发和收入。",
          chinaPosition: "模型追近，产品与商业化进入真正考验。",
        },
      ],
    },
    {
      slug: "model-economics",
      thesis: "单位 token 价格仍在下降，但真正重要的成本单位正在变成一次可靠完成的任务。",
      now: "MoE、FP8、推理预算和模型路由共同决定成本曲线。",
      next: "采购需要比较成功率、重试、延迟、人工接管和总拥有成本。",
      stages: [
        {
          period: "2024 H2",
          label: "Token price",
          summary: "开放模型和云竞争压低 API 单价。",
          chinaPosition: "国内价格战扩大模型可及性。",
        },
        {
          period: "2025",
          label: "Reasoning budget",
          summary: "推理时计算让成本随任务难度变化。",
          chinaPosition: "DeepSeek 把效率与价格变成全球竞争力。",
        },
        {
          period: "2026 H1",
          label: "Cost per outcome",
          summary: "采购转向按可靠任务结果衡量。",
          chinaPosition: "需要补齐真实 ROI、SLA 和企业交付证据。",
        },
      ],
    },
  ],
} as const;
